spring:
  datasource:
    url : jdbc:h2:mem:testDb
    password: sa
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  cache:
    type: redis


  redis:
    host: localhost
    port: 6380

cache:
  config:
    entryTtl : 60
    countryName :
      entryTtl : 30

